### ISSUE TITLE
Some imports fail with no way to retry them

### ISSUE THREAD

**Issue by mintindeed** [Penske-Media-Corp/pmc-theme-unit-test#1]
User feedback stating why the import failed would be useful, as well as a way to retry (preferably automated retry).

<img width="564" alt="screenshot 2015-07-29 08 41 07" src="https://cloud.githubusercontent.com/assets/468396/8962162/f01a58a8-35cd-11e5-84d3-5e646b56621f.png">

**Comment by amandhare** [comment]
Users can check the error.log file and find if anything failed and why. 

Users can click the Import From Production button multiple times and there will be no duplication of data. They will only get new data that was not imported before.

I am working towards catching the errors and better logging it so that we know what failed and why.

**Comment by amandhare** [comment]
Feature has been added to import a specific endpoint by clicking the Import button next to it. Details regarding failed imports can be checked in import.log file.
